version: '3'

services:
  postgres:
    container_name: postgres-laborexchange
    image: postgres:16.4
    environment:
      POSTGRES_DB: "labor-exchange"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

  postgres-test:
    container_name: postgres-laborexchange-test
    image: postgres:16.4
    environment:
      POSTGRES_DB: "labor-exchange"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
      - postgres-test:/data/postgres
    ports:
      - "5433:5432"

volumes:
    postgres:
    postgres-test:
