"""ru fix

Revision ID: be9d97f54a56
Revises: 6136d0ea90a3
Create Date: 2024-12-16 23:09:06.708458

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be9d97f54a56"
down_revision = "6136d0ea90a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "title",
        existing_type=sa.VARCHAR(),
        comment="Название вакансии",
        existing_comment="Yfpd dft",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "description",
        existing_type=sa.VARCHAR(),
        comment="Описание вакансии",
        existing_comment="jgbcfybt dfr",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "salary_from",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Зарплата от",
        existing_comment="pfgh",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "salary_to",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Зарплата до",
        existing_comment="zp do",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="Активна ли вакансия",
        existing_comment="frnb",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания записи",
        existing_comment="Data sozd str",
        existing_nullable=False,
    )
    op.alter_column(
        "responses",
        "message",
        existing_type=sa.VARCHAR(),
        comment="Сопроводительное письмо",
        existing_comment="Cjg",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "responses",
        "message",
        existing_type=sa.VARCHAR(),
        comment="Cjg",
        existing_comment="Сопроводительное письмо",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Data sozd str",
        existing_comment="Дата создания записи",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="frnb",
        existing_comment="Активна ли вакансия",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "salary_to",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="zp do",
        existing_comment="Зарплата до",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "salary_from",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="pfgh",
        existing_comment="Зарплата от",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "description",
        existing_type=sa.VARCHAR(),
        comment="jgbcfybt dfr",
        existing_comment="Описание вакансии",
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "title",
        existing_type=sa.VARCHAR(),
        comment="Yfpd dft",
        existing_comment="Название вакансии",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
