"""init?

Revision ID: 6136d0ea90a3
Revises: e31beef93767
Create Date: 2024-12-16 13:57:16.709927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6136d0ea90a3'
down_revision = 'e31beef93767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False, comment='Yfpd dft'))
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=False, comment='jgbcfybt dfr'))
    op.add_column('jobs', sa.Column('salary_from', sa.Numeric(precision=10, scale=2), nullable=False, comment='pfgh'))
    op.add_column('jobs', sa.Column('salary_to', sa.Numeric(precision=10, scale=2), nullable=False, comment='zp do'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='frnb'))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data sozd str'))
    op.add_column('responses', sa.Column('message', sa.String(), nullable=False, comment='Cjg'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
